### ISSUE TITLE
Update details views to show pos and neg results

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#48]
For presumptive and positive registers, the detail views should show both pos and neg results.

**Comment by rowo** [comment]
@cagulas In the meeting, did you talk about the "results comparison" box in in-treatment details view? I think it'd be useful as a way to show baseline vs. recent results. Also, is the content of positive results during in-treatment finalized? Instead of first encounter date, it highlights the treatment start date.

Presumptive and Positive detail results box:

![tb-presumptive-positive](https://user-images.githubusercontent.com/1584163/33907747-33c2eaac-df54-11e7-9c8f-d8046d2d82e8.png)


In-treatment detail results box options:

![tb-in-treatment](https://user-images.githubusercontent.com/1584163/33907879-a15d854a-df54-11e7-9adf-6d9deb0cfadf.png)

**Comment by cagulas** [comment]
For the presumptive and positive, I would remove "positive" from "no positive results recorded" because this is now showing all results.

The results comparison for the in-treatment looks good. I think it should show even negative results at the baseline as well.

**Comment by rowo** [comment]
@cagulas Thanks, here are updated screens. Added dates and month of treatement to positive results box as well since that will only be used during in-treatment.

![results01](https://user-images.githubusercontent.com/1584163/33972501-2173d1ba-e04c-11e7-880e-0739a5990b5f.png)

![results02](https://user-images.githubusercontent.com/1584163/33972508-267abe62-e04c-11e7-9f87-b69d6573e97f.png)

**Comment by cagulas** [comment]
@rowo This looks good, but I'm not sure what the "Positive Results" box is for? Wouldn't only the "Results Comparison" box need to be shown in the in-treatment register?

**Comment by rowo** [comment]
@cagulas It is for if people don't want to show the results comparison in case that ever happens. So they represent two configurable options. We could just say for that in-treatment, it only shows the comparison — that's definitely an option.

**Comment by cagulas** [comment]
I think it wouldn't happen to only look at positive results. Because they compare progress to baseline always to see if they're getting better. If they aren't improving from baseline, they might have to do additional tests (like for MDR-TB) or switch medications. I think we're ok with only doing the comparison. Does that sound ok?

**Comment by rowo** [comment]
I get why comparison is important and how that all works. I did originally propose the combined view after all. I'd also love to do a chart version if we ever get to a v2. Maybe a single result mapped over time since the tests are more limited during treatment.

Providing an alternate view is more about if due to constraints or workflow, the positive results is all they have and you don't want to force someone to make up baseline results or something like that. So if that's never going to be a possibility, we can get rid of it and force the comparison view. Alternatively, another way to handle that is by showing a case where baseline results don't exist (for whatever reason), but you show the earliest result taken. I don't know how this impacts the form.

**Comment by cagulas** [comment]
I can't think of a situation where baseline results wouldn't exist in the app. They wouldn't start treatment without baseline results entered. If they transfer in from another place and don't have their baseline results with them, they'd test them again, and they'd use those as the baseline results (if they can't get the original results).

**Comment by rowo** [comment]
Ok no positive results sounds good if that's the only workflow. I updated the screen above.

**Comment by cagulas** [comment]
Closing this issue. Created https://github.com/OpenSRP/opensrp-client-tbr/issues/57 and https://github.com/OpenSRP/opensrp-client-tbr/issues/56 for implementation.
