### ISSUE TITLE
Update Smear results in configurable columns

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#53]
I think it would be helpful to show the different options for Smear results in the configurable column, because there might be a spacing issue, so hopefully you can tell us.

I'm referring to comments from Wasim in https://github.com/OpenSRP/opensrp-client-tbr/issues/34#issuecomment-346312569.

- [x] In the Smear result form, the smear result answer choices (and the suggested label for the configurable column in parentheses) are:
- `3+` (3+)
- `2+` (2+)
- `1+` (1+)
- `scanty` (Scanty)
- `negative` (Negative)

Note 1: Wasim suggested in https://github.com/OpenSRP/opensrp-client-tbr/issues/34#issuecomment-346312569 to use "Sty" for scanty and "Neg" for negative, but since this is the only result shown, I think we can show the full word.

Note 2: All answer choices except negative are red font, while negative would be black font.

**Comment by alihabib** [comment]
If Negative is too long "-" will also work. I'd say leave scanty red as well

Ali Habib
Chief Executive Officer
Interactive Health Solutions
http://www.ihsinformatics.com

ali.habib@ihsinformatics.com

**Comment by rowo** [comment]
![smrresults](https://user-images.githubusercontent.com/1584163/34734994-d3995fc8-f53b-11e7-98f1-b09206cea309.png)

Here's a look at smear results in the SMR-only and results columns. So, to add or finalize what's above — we'll show any positive or scanty result in #c30000 whereas Negative shows up in #191919. When the column is smear result only, the full text can be shown for Scanty and Negative. When it's the smear result in an all results column, the text is shortened to Sty and Neg so that a culture result can fit.

**Comment by cagulas** [comment]
Great, thanks @rowo. Think this looks great.

**Comment by cagulas** [comment]
@githengi @ndegwamartin Ok, this one is ready to go. Please note how the smear results have to be abbreviated in the more general results column.

**Comment by cagulas** [comment]
Lgtm
